packaging_format = 2

id = "pmwiki"
name = "PmWiki"
description.en = "wiki-based content-management system (CMS) for collaborative creation and maintenance of websites"
description.fr = "Système de type wiki pour la création et l'entretien collectif de sites Internet"

version = "2.3.21~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-2.0-only"
website = "https://www.pmwiki.org"
admindoc = "https://www.pmwiki.org/wiki/PmWikiFr/PmWikiFr"
userdoc = "https://www.pmwiki.org/wiki/PmWikiFr/PmWikiUsers"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pmwiki"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://www.pmwiki.org/pub/pmwiki/pmwiki-2.3.21.zip"
        sha256 = "665d4f7c719fe7159dedc088dae8fa2c7e3f6b18ef424001b26ee0b4741f6998"

        [resources.sources.fr]
        url = "http://www.pmwiki.org/pub/pmwiki/i18n/i18n-fr.zip"
        sha256 = "0dc3b6d80dd165d0ef62d5cd2eeac9552145d70c9171c6ee287af9035b22227f"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.0-fpm"
