packaging_format = 2

id = "pmwiki"
name = "PmWiki"
description.en = "wiki-based content-management system (CMS) for collaborative creation and maintenance of websites"
description.fr = "Système de type wiki pour la création et l'entretien collectif de sites Internet"

version = "2.3.21~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-2.0-only"
website = "https://www.pmwiki.org"
admindoc = "https://www.pmwiki.org/wiki/PmWikiFr/PmWikiFr"
userdoc = "https://www.pmwiki.org/wiki/PmWikiFr/PmWikiUsers"

[integration]
yunohost = ">= 11.1.18"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pmwiki"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://www.pmwiki.org/pub/pmwiki/pmwiki-2.3.23.zip"
        sha256 = "6f2444fa162c304f085824432b307fb46639740db3104a50aa9549ba94a42861"

        [resources.sources.fr]
        url = "http://www.pmwiki.org/pub/pmwiki/i18n/i18n-fr.zip"
        sha256 = "7e63d82a4b7d45e12721756acec2963bd9289eb6a4d6c56b4bf7dddc226f6bd7"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.0-fpm"
