packaging_format = 2

id = "pmwiki"
name = "PmWiki"
description.en = "Wiki-based CMS for collaborative creation and maintenance of websites"
description.fr = "Wiki pour la création et l'entretien collectif de sites Internet"

version = "2.3.32~ynh7"

maintainers = [ ]

[upstream]
license = "GPL-2.0-only"
website = "https://www.pmwiki.org"
admindoc = "https://www.pmwiki.org/wiki/PmWikiFr/PmWikiFr"
userdoc = "https://www.pmwiki.org/wiki/PmWikiFr/PmWikiUsers"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/pmwiki"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://www.pmwiki.org/pub/pmwiki/pmwiki-2.3.32.zip"
        sha256 = "5e0a4f990802ae9dfd83837d3484557d93e08ace9df0f294e8198440c5f7534b"

        [resources.sources.fr]
        url = "http://www.pmwiki.org/pub/pmwiki/i18n/i18n-fr.zip"
        sha256 = "b4660a91b77fc05a52c6126315b10169936865e14bf002ed9be5ccf442b49cf9"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-fpm"
