#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=100M

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

timezone=$(cat /etc/timezone)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

ynh_setup_source --dest_dir="$install_dir/wikilib.d" --source_id=fr

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

ynh_config_add_phpfpm

ynh_config_add_logrotate

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.php" --destination="$install_dir/local/config.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
